-- Migration 003: Seed Roles
-- Insert all 36 roles from DOA_DATA.roles plus the extra threshold-only role

INSERT INTO roles (name, sort_order) VALUES
('General Assembly', 1),
('BOD', 2),
('ExCom', 3),
('NRC', 4),
('Audit Committee', 5),
('Risk & Sustainability', 6),
('CEO', 7),
('COO', 8),
('CFO', 9),
('CTO', 10),
('EPF', 11),
('Strategy & Corp Dev', 12),
('Corporate Services', 13),
('Chief of Staff', 14),
('General Counsel', 15),
('Marketing & Commercial', 16),
('QHSE', 17),
('Internal Audit', 18),
('VP HR', 19),
('VP GRC', 20),
('VP Supply Chain', 21),
('Group Financial Controller', 22),
('FP&A Director', 23),
('Tax Director', 24),
('Treasury Director', 25),
('Commercial Director', 26),
('VP Geographies', 27),
('Head of PSL', 28),
('Country Manager', 29),
('Country Finance Lead', 30),
('PSL/EPF Director', 31),
('Procurement & Sourcing Director', 32),
('Supply Chain Ops Director', 33),
('HR Business Partner', 34),
('Support Dept Head', 35),
('Manufacturing/Eng Manager', 36),
('PSL/CoE/EPF Finance Controller', 37);
