-- Migration 006: Seed Countries
-- Insert all countries with risk_level classification:
--   'safe'      = In DEFAULT_SAFE_COUNTRIES but NOT in DEFAULT_SPECIAL_COUNTRIES
--   'special'   = In DEFAULT_SPECIAL_COUNTRIES (regardless of safe status)
--   'high_risk' = Not in either list
--
-- DEFAULT_SAFE_COUNTRIES: Bahrain, Bangladesh, Egypt, India, Iraq - Kurdistan,
--   Iraq - South, Kuwait, Libya, Oman, Pakistan, Qatar, Saudi Arabia, Turkey,
--   United Arab Emirates
--
-- DEFAULT_SPECIAL_COUNTRIES: Algeria, Egypt, Iraq - South, Libya, Pakistan
--
-- Overlap (safe AND special -> 'special'): Egypt, Iraq - South, Libya, Pakistan
-- Special only (not safe -> 'special'): Algeria
-- Safe only (not special -> 'safe'): Bahrain, Bangladesh, India, Iraq - Kurdistan,
--   Kuwait, Oman, Qatar, Saudi Arabia, Turkey, United Arab Emirates

INSERT INTO countries (name, risk_level) VALUES
('Afghanistan', 'high_risk'),
('Albania', 'high_risk'),
('Algeria', 'special'),
('Angola', 'high_risk'),
('Argentina', 'high_risk'),
('Armenia', 'high_risk'),
('Australia', 'high_risk'),
('Austria', 'high_risk'),
('Azerbaijan', 'high_risk'),
('Bahrain', 'safe'),
('Bangladesh', 'safe'),
('Belarus', 'high_risk'),
('Belgium', 'high_risk'),
('Bolivia', 'high_risk'),
('Bosnia and Herzegovina', 'high_risk'),
('Brazil', 'high_risk'),
('Brunei', 'high_risk'),
('Bulgaria', 'high_risk'),
('Cameroon', 'high_risk'),
('Canada', 'high_risk'),
('Chad', 'high_risk'),
('Chile', 'high_risk'),
('China', 'high_risk'),
('Colombia', 'high_risk'),
('Congo', 'high_risk'),
('Croatia', 'high_risk'),
('Cuba', 'high_risk'),
('Cyprus', 'high_risk'),
('Czech Republic', 'high_risk'),
('Denmark', 'high_risk'),
('Ecuador', 'high_risk'),
('Egypt', 'special'),
('Equatorial Guinea', 'high_risk'),
('Estonia', 'high_risk'),
('Ethiopia', 'high_risk'),
('Finland', 'high_risk'),
('France', 'high_risk'),
('Gabon', 'high_risk'),
('Georgia', 'high_risk'),
('Germany', 'high_risk'),
('Ghana', 'high_risk'),
('Greece', 'high_risk'),
('Hungary', 'high_risk'),
('India', 'safe'),
('Indonesia', 'high_risk'),
('Iran', 'high_risk'),
('Iraq - Kurdistan', 'safe'),
('Iraq - South', 'special'),
('Ireland', 'high_risk'),
('Israel', 'high_risk'),
('Italy', 'high_risk'),
('Ivory Coast', 'high_risk'),
('Japan', 'high_risk'),
('Jordan', 'high_risk'),
('Kazakhstan', 'high_risk'),
('Kenya', 'high_risk'),
('Kuwait', 'safe'),
('Kyrgyzstan', 'high_risk'),
('Latvia', 'high_risk'),
('Lebanon', 'high_risk'),
('Libya', 'special'),
('Lithuania', 'high_risk'),
('Luxembourg', 'high_risk'),
('Malaysia', 'high_risk'),
('Mali', 'high_risk'),
('Mauritania', 'high_risk'),
('Mexico', 'high_risk'),
('Mongolia', 'high_risk'),
('Morocco', 'high_risk'),
('Mozambique', 'high_risk'),
('Myanmar', 'high_risk'),
('Netherlands', 'high_risk'),
('New Zealand', 'high_risk'),
('Niger', 'high_risk'),
('Nigeria', 'high_risk'),
('North Korea', 'high_risk'),
('Norway', 'high_risk'),
('Oman', 'safe'),
('Pakistan', 'special'),
('Panama', 'high_risk'),
('Papua New Guinea', 'high_risk'),
('Peru', 'high_risk'),
('Philippines', 'high_risk'),
('Poland', 'high_risk'),
('Portugal', 'high_risk'),
('Qatar', 'safe'),
('Romania', 'high_risk'),
('Russia', 'high_risk'),
('Saudi Arabia', 'safe'),
('Senegal', 'high_risk'),
('Serbia', 'high_risk'),
('Singapore', 'high_risk'),
('Slovakia', 'high_risk'),
('Slovenia', 'high_risk'),
('Somalia', 'high_risk'),
('South Africa', 'high_risk'),
('South Korea', 'high_risk'),
('South Sudan', 'high_risk'),
('Spain', 'high_risk'),
('Sri Lanka', 'high_risk'),
('Sudan', 'high_risk'),
('Sweden', 'high_risk'),
('Switzerland', 'high_risk'),
('Syria', 'high_risk'),
('Taiwan', 'high_risk'),
('Tajikistan', 'high_risk'),
('Tanzania', 'high_risk'),
('Thailand', 'high_risk'),
('Trinidad and Tobago', 'high_risk'),
('Tunisia', 'high_risk'),
('Turkey', 'safe'),
('Turkmenistan', 'high_risk'),
('Uganda', 'high_risk'),
('Ukraine', 'high_risk'),
('United Arab Emirates', 'safe'),
('United Kingdom', 'high_risk'),
('United States', 'high_risk'),
('Uzbekistan', 'high_risk'),
('Venezuela', 'high_risk'),
('Vietnam', 'high_risk'),
('Yemen', 'high_risk'),
('Zambia', 'high_risk'),
('Zimbabwe', 'high_risk');
